name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create install directory
        run: mkdir -p ~/dotfiles-install-dir

      - name: Install dotfiles
        run: HOME=~/dotfiles-install-dir ./install
