name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Install pre-requisites
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Provision environment
        run: ansible-playbook ansible/playbooks/main.yml -vvv

      - name: Run checks
        run: prek run --all-files --verbose
